FROM node:10
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
ARG NEXT_PUBLIC_API_URI
ENV NEXT_PUBLIC_API_URI ${NEXT_PUBLIC_API_URI:-http://localhost:8000/graphql/}

EXPOSE 3000
CMD npm start
