// tslint:disable:object-literal-sort-keys
export const items = [
  {
    id: "TWVudUl0ZW06Mjcx",
    name: "Accessories",
    category: {
      slug: "accessories",
      id: "Q2F0ZWdvcnk6Nw==",
      name: "Accessories",
      __typename: "Category",
    },
    url: null,
    collection: null,
    page: null,
    parent: null,
    __typename: "MenuItem",
    children: [
      {
        id: "123",
        name: "Subcategory I",
        category: {
          id: "Q2F0ZWdvcnk6Nw==",
          name: "Accessories",
          __typename: "Category",
          slug: "category",
        },
        url: null,
        collection: null,
        page: null,
        parent: null,
        __typename: "MenuItem",
        children: [
          {
            id: "TWVudUl0ZW01Mjcx",
            name: "Subsubcategory I",
            category: {
              id: "Q2F0ZWdvcnk6Nw==",
              name: "Accessories",
              __typename: "Category",
              slug: "category",
            },
          },
        ],
      },
      {
        id: "TWVudUl0ZW01Mjcx",
        name: "Subcategory II",
        category: {
          id: "Q2F0ZWdvcnk6Nw==",
          name: "Accessories",
          slug: "accessories",
          __typename: "Category",
        },
        url: null,
        collection: null,
        page: null,
        parent: null,
        __typename: "MenuItem",
        children: [],
      },
    ],
  },
  {
    id: "TWVudUl0ZW06Mjcy",
    name: "Groceries",
    category: {
      slug: "groceries",
      id: "Q2F0ZWdvcnk6OA==",
      name: "Groceries",
      __typename: "Category",
    },
    url: null,
    collection: null,
    page: null,
    parent: null,
    __typename: "MenuItem",
    children: [],
  },
  {
    id: "TWVudUl0ZW06Mjcz",
    name: "Apparel",
    category: {
      slug: "aroceries",
      id: "Q2F0ZWdvcnk6OQ==",
      name: "Apparel",
      __typename: "Category",
    },
    url: null,
    collection: null,
    page: null,
    parent: null,
    __typename: "MenuItem",
    children: [],
  },
];
