export const COUNTRY_LIST = [
  {
    value: "AF",
    text: "Afghanistan",
    code: "+93",
  },
  { value: "AX", text: "\xc5land Islands", code: "+500" },
  { value: "AL", text: "Albania", code: "+355" },
  { value: "DZ", text: "Algeria", code: "+213" },
  { value: "AS", text: "American Samoa", code: "+684" },
  { value: "AD", text: "Andorra", code: "+376" },
  { value: "AO", text: "Angola", code: "+244" },
  { value: "AI", text: "Anguilla", code: "+1264" },
  { value: "AQ", text: "Antarctica", code: "" },
  { value: "AG", text: "Antigua And Barbuda", code: "+1268" },
  { value: "AR", text: "Argentina", code: "+54" },
  { value: "AM", text: "Armenia", code: "+374" },
  { value: "AW", text: "Aruba", code: "+297" },
  { value: "AU", text: "Australia", code: "+61" },
  { value: "AT", text: "Austria", code: "+43" },
  { value: "AZ", text: "Azerbaijan", code: "+994" },
  { value: "BS", text: "Bahamas", code: "+1242" },
  { value: "BH", text: "Bahrain", code: "+973" },
  { value: "BD", text: "Bangladesh", code: "+880" },
  { value: "BB", text: "Barbados", code: "+1246" },
  { value: "BY", text: "Belarus", code: "+375" },
  { value: "BE", text: "Belgium", code: "+32" },
  { value: "BZ", text: "Belize", code: "+501" },
  { value: "BJ", text: "Benin", code: "+229" },
  { value: "BM", text: "Bermuda", code: "+1441" },
  { value: "BT", text: "Bhutan", code: "+975" },
  { value: "BO", text: "Bolivia", code: "+591" },
  { value: "BQ", text: "Bonaire, Saint Eustatius And Saba", code: "" },
  { value: "BA", text: "Bosnia And Herzegovina", code: "+387" },
  { value: "BW", text: "Botswana", code: "+267" },
  { value: "BV", text: "Bouvet Island", code: "" },
  { value: "BR", text: "Brazil", code: "+55" },
  { value: "IO", text: "British Indian Ocean Territory", code: "" },
  { value: "BN", text: "Brunei Darussalam", code: "+673" },
  { value: "BG", text: "Bulgaria", code: "+359" },
  { value: "BF", text: "Burkina Faso", code: "+226" },
  { value: "BI", text: "Burundi", code: "+257" },
  { value: "KH", text: "Cambodia", code: "+855" },
  { value: "CM", text: "Cameroon", code: "+237" },
  { value: "CA", text: "Canada", code: "+1" },
  { value: "CV", text: "Cape Verde", code: "+238" },
  { value: "KY", text: "Cayman Islands", code: "+1345" },
  { value: "CF", text: "Central African Republic", code: "+236" },
  { value: "TD", text: "Chad", code: "+235" },
  { value: "CL", text: "Chile", code: "+56" },
  { value: "CN", text: "China", code: "+86" },
  { value: "CX", text: "Christmas Island", code: "" },
  { value: "CC", text: "Cocos (Keeling) Islands", code: "" },
  { value: "CO", text: "Colombia", code: "+57" },
  { value: "KM", text: "Comoros", code: "+269" },
  { value: "CG", text: "Congo", code: "+242" },
  { value: "CD", text: "Congo, The Democratic Republic of the", code: "+243" },
  { value: "CK", text: "Cook Islands", code: "+682" },
  { value: "CR", text: "Costa Rica", code: "+506" },
  { value: "CI", text: "C\xf4te D'Ivoire", code: "" },
  { value: "HR", text: "Croatia", code: "+385" },
  { value: "CU", text: "Cuba", code: "+53" },
  { value: "CW", text: "Cura\xe7o", code: "" },
  { value: "CY", text: "Cyprus", code: "+357" },
  { value: "CZ", text: "Czech Republic", code: "+420" },
  { value: "DK", text: "Denmark", code: "+45" },
  { value: "DJ", text: "Djibouti", code: "+253" },
  { value: "DM", text: "Dominica", code: "+1767" },
  { value: "DO", text: "Dominican Republic", code: "+1809" },
  { value: "EC", text: "Ecuador", code: "+593" },
  { value: "EG", text: "Egypt", code: "+20" },
  { value: "SV", text: "El Salvador", code: "+503" },
  { value: "GQ", text: "Equatorial Guinea", code: "+240" },
  { value: "ER", text: "Eritrea", code: "" },
  { value: "EE", text: "Estonia", code: "+372" },
  { value: "ET", text: "Ethiopia", code: "+251" },
  { value: "FK", text: "Falkland Islands (Malvinas)", code: "+500" },
  { value: "FO", text: "Faroe Islands", code: "" },
  { value: "FJ", text: "Fiji", code: "+679" },
  { value: "FI", text: "Finland", code: "+358" },
  { value: "FR", text: "France", code: "+33" },
  { value: "GF", text: "French Guiana", code: "+594" },
  { value: "PF", text: "French Polynesia", code: "+689" },
  { value: "TF", text: "French Southern Territories", code: "" },
  { value: "GA", text: "Gabon", code: "+241" },
  { value: "GM", text: "Gambia", code: "+220" },
  { value: "GE", text: "Georgia", code: "+995" },
  { value: "DE", text: "Germany", code: "+49" },
  { value: "GH", text: "Ghana", code: "+233" },
  { value: "GI", text: "Gibraltar", code: "+350" },
  { value: "GR", text: "Greece", code: "+30" },
  { value: "GL", text: "Greenland", code: "+299" },
  { value: "GD", text: "Grenada", code: "+1473" },
  { value: "GP", text: "Guadeloupe", code: "+590" },
  { value: "GU", text: "Guam", code: "+1671" },
  { value: "GT", text: "Guatemala", code: "+502" },
  { value: "GG", text: "Guernsey", code: "" },
  { value: "GN", text: "Guinea", code: "+224" },
  { value: "GW", text: "Guinea-Bissau", code: "+245" },
  { value: "GY", text: "Guyana", code: "+592" },
  { value: "HT", text: "Haiti", code: "+509" },
  { value: "HM", text: "Heard Island And Mcdonald Islands", code: "" },
  { value: "VA", text: "Holy See (Vatican City State)", code: "" },
  { value: "HN", text: "Honduras", code: "+504" },
  { value: "HK", text: "Hong Kong", code: "+852" },
  { value: "HU", text: "Hungary", code: "+36" },
  { value: "IS", text: "Iceland", code: "+354" },
  { value: "IN", text: "India", code: "+91" },
  { value: "ID", text: "Indonesia", code: "+62" },
  { value: "IR", text: "Iran, Islamic Republic of", code: "+98" },
  { value: "IQ", text: "Iraq", code: "+964" },
  { value: "IE", text: "Ireland", code: "+353" },
  { value: "IM", text: "Isle of Man", code: "" },
  { value: "IL", text: "Israel", code: "+972" },
  { value: "IT", text: "Italy", code: "+39" },
  { value: "JM", text: "Jamaica", code: "+1876" },
  { value: "JP", text: "Japan", code: "+81" },
  { value: "JE", text: "Jersey", code: "" },
  { value: "JO", text: "Jordan", code: "+962" },
  { value: "KZ", text: "Kazakhstan", code: "+76" },
  { value: "KE", text: "Kenya", code: "+254" },
  { value: "KI", text: "Kiribati", code: "" },
  { value: "KP", text: "Korea, Democratic People's Republic of", code: "+850" },
  { value: "KR", text: "Korea, Republic of", code: "+82" },
  { value: "KW", text: "Kuwait", code: "+965" },
  { value: "KG", text: "Kyrgyzstan", code: "+996" },
  { value: "LA", text: "Lao People's Democratic Republic", code: "" },
  { value: "LV", text: "Latvia", code: "+371" },
  { value: "LB", text: "Lebanon", code: "+961" },
  { value: "LS", text: "Lesotho", code: "+266" },
  { value: "LR", text: "Liberia", code: "+231" },
  { value: "LY", text: "Libya", code: "+218" },
  { value: "LI", text: "Liechtenstein", code: "+423" },
  { value: "LT", text: "Lithuania", code: "+370" },
  { value: "LU", text: "Luxembourg", code: "+352" },
  { value: "MO", text: "Macao", code: "" },
  {
    value: "MK",
    text: "Macedonia, The Former Yugoslav Republic of",
    code: "+389",
  },
  { value: "MG", text: "Madagascar", code: "+261" },
  { value: "MW", text: "Malawi", code: "+265" },
  { value: "MY", text: "Malaysia", code: "+60" },
  { value: "MV", text: "Maldives", code: "+960" },
  { value: "ML", text: "Mali", code: "+223" },
  { value: "MT", text: "Malta", code: "+356" },
  { value: "MH", text: "Marshall Islands", code: "	+692" },
  { value: "MQ", text: "Martinique", code: "+596" },
  { value: "MR", text: "Mauritania", code: "+222" },
  { value: "MU", text: "Mauritius", code: "+230" },
  { value: "YT", text: "Mayotte", code: "" },
  { value: "MX", text: "Mexico", code: "+52" },
  // ---------------------------------------------------------------------------- //
  { value: "FM", text: "Micronesia, Federated States of", code: "" },
  { value: "MD", text: "Moldova, Republic of", code: "+373" },
  { value: "MC", text: "Monaco", code: "+377" },
  { value: "MN", text: "Mongolia", code: "+976" },
  { value: "ME", text: "Montenegro", code: "+381" },
  { value: "MS", text: "Montserrat", code: "+1 664" },
  { value: "MA", text: "Morocco", code: "+212" },
  { value: "MZ", text: "Mozambique", code: "+258" },
  { value: "MM", text: "Myanmar", code: "+95" },
  { value: "NA", text: "Namibia", code: "+264" },
  { value: "NR", text: "Nauru", code: "" },
  { value: "NP", text: "Nepal", code: "+977" },
  { value: "NL", text: "Netherlands", code: "+31" },
  { value: "NC", text: "New Caledonia", code: "+687" },
  { value: "NZ", text: "New Zealand", code: "+64" },
  { value: "NI", text: "Nicaragua", code: "+505" },
  { value: "NE", text: "Niger", code: "+227" },
  { value: "NG", text: "Nigeria", code: "+234" },
  { value: "NU", text: "Niue", code: "" },
  { value: "NF", text: "Norfolk Island", code: "" },
  { value: "MP", text: "Northern Mariana Islands", code: "" },
  { value: "NO", text: "Norway", code: "+47" },
  { value: "OM", text: "Oman", code: "+968" },
  { value: "PK", text: "Pakistan", code: "+92" },
  { value: "PW", text: "Palau", code: "+680" },
  { value: "PS", text: "Palestinian Territory, Occupied", code: "" },
  { value: "PA", text: "Panama", code: "+507" },
  { value: "PG", text: "Papua New Guinea", code: "+675" },
  { value: "PY", text: "Paraguay", code: "+595" },
  { value: "PE", text: "Peru", code: "+51" },
  { value: "PH", text: "Philippines", code: "+63" },
  { value: "PN", text: "Pitcairn", code: "" },
  { value: "PL", text: "Poland", code: "+48" },
  { value: "PT", text: "Portugal", code: "+351" },
  { value: "PR", text: "Puerto Rico", code: "+1787, +1939" },
  { value: "QA", text: "Qatar", code: "+974" },
  { value: "RE", text: "R\xe9union", code: "" },
  { value: "RO", text: "Romania", code: "+40" },
  { value: "RU", text: "Russian Federation", code: "+7" },
  { value: "RW", text: "Rwanda", code: "+250" },
  { value: "BL", text: "Saint Barth\xe9lemy", code: "" },
  {
    value: "SH",
    text: "Saint Helena, Ascension And Tristan Da Cunha",
    code: "",
  },
  { value: "KN", text: "Saint Kitts And Nevis", code: "" },
  { value: "LC", text: "Saint Lucia", code: "" },
  { value: "MF", text: "Saint Martin (French Part)", code: "" },
  { value: "PM", text: "Saint Pierre And Miquelon", code: "" },
  { value: "VC", text: "Saint Vincent And the Grenadines", code: "" },
  { value: "WS", text: "Samoa", code: "+684" },
  { value: "SM", text: "San Marino", code: "+378" },
  { value: "ST", text: "Sao Tome And Principe", code: "" },
  { value: "SA", text: "Saudi Arabia", code: "+966" },
  { value: "SN", text: "Senegal", code: "+221" },
  { value: "RS", text: "Serbia", code: "+381" },
  { value: "SC", text: "Seychelles", code: "+248" },
  { value: "SL", text: "Sierra Leone", code: "+232" },
  { value: "SG", text: "Singapore", code: "+65" },
  { value: "SX", text: "Sint Maarten (Dutch Part)", code: "" },
  { value: "SK", text: "Slovakia", code: "" },
  { value: "SI", text: "Slovenia", code: "+386" },
  { value: "SB", text: "Solomon Islands", code: "+677" },
  { value: "SO", text: "Somalia", code: "+252" },
  { value: "ZA", text: "South Africa", code: "+27" },
  {
    value: "GS",
    text: "South Georgia and the South Sandwich Islands",
    code: "",
  },
  { value: "ES", text: "Spain", code: "+34" },
  { value: "LK", text: "Sri Lanka", code: "+94" },
  { value: "SD", text: "Sudan", code: "+249" },
  { value: "SR", text: "Suriname", code: "+597" },
  { value: "SJ", text: "Svalbard and Jan Mayen", code: "" },
  { value: "SZ", text: "Swaziland", code: "+268" },
  { value: "SE", text: "Sweden", code: "+46" },
  { value: "CH", text: "Switzerland", code: "+41" },
  { value: "SY", text: "Syria", code: "+963" },
  { value: "TW", text: "Taiwan", code: "+886" },
  { value: "TJ", text: "Tajikistan", code: "+992" },
  { value: "TZ", text: "Tanzania", code: "+255" },
  { value: "TH", text: "Thailand", code: "+66" },
  { value: "TL", text: "Timor-Leste", code: "" },
  { value: "TG", text: "Togo", code: "+228" },
  { value: "TK", text: "Tokelau", code: "" },
  { value: "TO", text: "Tonga", code: "+676" },
  { value: "TT", text: "Trinidad And Tobago", code: "" },
  { value: "TN", text: "Tunisia", code: "+216" },
  { value: "TR", text: "Turkey", code: "+90" },
  { value: "TM", text: "Turkmenistan", code: "+993" },
  { value: "TC", text: "Turks And Caicos Islands", code: "+1 649" },
  { value: "TV", text: "Tuvalu", code: "+688" },
  { value: "UG", text: "Uganda", code: "+256" },
  { value: "UA", text: "Ukraine", code: "+380" },
  { value: "AE", text: "United Arab Emirates", code: "+971" },
  { value: "GB", text: "United Kingdom", code: "+44" },
  { value: "US", text: "United States", code: "+1" },
  { value: "UM", text: "United States Minor Outlying Islands", code: "+1" },
  { value: "UY", text: "Uruguay", code: "+598" },
  { value: "UZ", text: "Uzbekistan", code: "+998" },
  { value: "VU", text: "Vanuatu", code: "+678" },
  { value: "VE", text: "Venezuela", code: "+58" },
  { value: "VN", text: "Viet Nam", code: "+84" },
  { value: "VG", text: "Virgin Islands, British", code: "+1 284" },
  { value: "VI", text: "Virgin Islands, U.S.", code: "+1 340" },
  { value: "WF", text: "Wallis And Futuna", code: "" },
  { value: "EH", text: "Western Sahara", code: "" },
  { value: "YE", text: "Yemen", code: "+967" },
  { value: "ZM", text: "Zambia", code: "+260" },
  { value: "ZW", text: "Zimbabwe", code: "+263" },
];
