name: Build'n push container image

on:
  push:
    tags:
      - v2.*
      - v3.*

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set-up doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Build container image
        env:
          API_URI: https://saleor-core-gqqct.ondigitalocean.app/graphql/
          # API_URI=${{ secrets.API_URI }}
        run: docker build --build-arg API_URI=$API_URI -t registry.digitalocean.com/zoe/saleor-storefront:$(echo $GITHUB_REF | cut -d\/ -f3) .
      - name: Log in to DigitalOcean Container Registry
        run: doctl registry login --expiry-seconds 1200
      - name: Push image to DigitalOcean Container Registry
        run: docker push registry.digitalocean.com/zoe/saleor-storefront:$(echo $GITHUB_REF | cut -d\/ -f3)
