name: QA

on:
  pull_request:
    branches: [ '*' ]

jobs:

  check-lock:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Validate lock file
      run: |
        npx lockfile-lint --path package-lock.json --allowed-hosts npm yarn

  tsc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run tsc
      run: |
        npm ci
        npm run tsc

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run tsc
      run: |
        npm ci
        npm run test